version: '3'

services:
  psql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5432:5432

  fastapi:
    build: .
    environment:
      - PYTHONBUFFERED=0
    volumes:
      - ./app:/code/app
    ports:
      - 80:80